-- CreateEnum
CREATE TYPE "Permission" AS ENUM ('VIEW_FINANCIALS_AND_REPORTS', 'MANAGE_PROPERTIES_AND_UNITS', 'VIEW_TENANTS_AND_LEASES', 'VIEW_MAINTENANCE_TICKETS', 'APPROVE_MAJOR_MAINTENANCE');

-- AlterTable
ALTER TABLE "user" ADD COLUMN     "permissions" "Permission"[] DEFAULT ARRAY[]::"Permission"[];
